### Crear el dataframe para la tabla Promociones

In [1]:
import pandas as pd
import os

In [8]:
ruta = "../../../base_datos_relacional_escuela/data/"

### Cargamos los csv

In [11]:
clase_1 = pd.read_csv(ruta + "clase_1.csv", sep=";")
clase_2 = pd.read_csv(ruta + "clase_2.csv", sep=";")
clase_3 = pd.read_csv(ruta + "clase_3.csv", sep=";")
clase_4 = pd.read_csv(ruta + "clase_4.csv", sep=";")
claustro = pd.read_csv(ruta + "claustro.csv", sep=";")

### Mostramos los dataframes

In [12]:
clase_1.head()

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto

In [13]:
clase_2.head()

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto
1,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto
2,Carlito Carrión,Carlito_Carrión@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,Apto
3,Haydée Figueroa,Haydée_Figueroa@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto
4,Chita Mancebo,Chita_Mancebo@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto

In [14]:
clase_3.head()

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto Plana,Cleto_Plana@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
3,Aitana Sebastián,Aitana_Sebastián@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
4,Dolores Valbuena,Dolores_Valbuena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto

In [15]:
clase_4.head()

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
1,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
2,Ernesto Uriarte,Ernesto_Uriarte@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
3,Daniela Guitart,Daniela_Guitart@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto
4,Timoteo Trillo,Timoteo_Trillo@gmail.com,Febrero,12/02/2024,Valencia,No Apto,Apto,Apto,Apto,No Apto

In [16]:
claustro.head()

              Nombre Rol Vertical   Promocion    Campus   Modalidad
0          Noa Yáñez  TA       DS  Septiembre    Madrid  Presencial
1  Saturnina Benitez  TA       DS  Septiembre    Madrid  Presencial
2         Anna Feliu  TA       FS  Septiembre    Madrid  Presencial
3      Rosalva Ayuso  TA       FS  Septiembre  Valencia  Presencial
4   Ana Sofía Ferrer  TA       FS     Febrero  Valencia  Presencial

### Importamos la tabla roles a un dataframe

In [22]:
from sqlalchemy import create_engine

### Conectamos a la base de datos

In [26]:
engine = create_engine("postgresql://roberto:TLH3dLYlrEUe5AYGTzl1zZILE0ke6mfQ@dpg-d86od7btqb8s73fpch2g-a.oregon-postgres.render.com/proyecto_bases_relacional")

### Miramos las tablas que hemos cargado

In [27]:
tablas = pd.read_sql("""
    SELECT table_schema, table_name 
    FROM information_schema.tables 
    WHERE table_type = 'BASE TABLE'
    AND table_schema NOT IN ('pg_catalog', 'information_schema')
""", engine)

print(tablas)

  table_schema    table_name
0       public         sedes
1       public        cursos
2       public         roles
3       public     proyectos
4       public   promociones
5       public   modalidades
6       public    profesores
7       public       alumnos
8       public         notas
9       public  asignaciones

### Cargamos la tabla roles

In [28]:
roles = pd.read_sql("SELECT * FROM roles", engine)
roles.head()

   id_rol codigo     nombre
0       2     TA  Asistente
1       3     LI   Profesor

### Extraemos nombre y rol del dataframe claustro

In [43]:
profesores = claustro[["Nombre", "Rol"]].copy()

### Merge del dataframe roles y profesores

In [44]:
profesores = profesores.merge(
    roles[["id_rol", "codigo"]],
    left_on="Rol",
    right_on="codigo",
    how="left"
)

### Extraemos las columnas necesarias y las cambiamos de nombre

In [45]:
profesores = profesores[["Nombre", "id_rol"]]
profesores.columns = ["nombre", "id_rol"]

### Insertamos en la tabla de la base de datos

In [ ]:
profesores.to_sql("profesores", engine, if_exists="append", index=False)

### En este punto miramos en la base de datos las tablas que ya están con los datos integrados:

* cursos: CON datos
* modalidades: CON datos
* profesores: CON datos
* roles: CON datos
* sedes: CON datos
* alumnos: SIN datos
* asignaciones: SIN datos
* promociones: SIN datos
* proyectos: SIN datos
* notas: SIN datos

### Empezamos con la inserción de datos en la tabla 'promociones'

### Cargar las tablas que tienen datos (sedes, modalidades, cursos)

In [48]:
sedes = pd.read_sql("SELECT * FROM sedes", engine)
modalidades = pd.read_sql("SELECT * FROM modalidades", engine)
cursos = pd.read_sql("SELECT * FROM cursos", engine)

### Miramos como son las tablas

In [49]:
print("SEDES:")
print(sedes)
print("\nMODALIDADES:")
print(modalidades)
print("\nCURSOS:")
print(cursos)

SEDES:
   id_sede    nombre
0        1    Madrid
1        2  Valencia

MODALIDADES:
   id_modalidad      nombre
0             2  Presencial
1             3      Online

CURSOS:
   id_curso codigo        nombre
0         1     DS  Data Science
1         2     FS    Full Stack

### Creamos el dataframe promociones (a mano)

In [50]:
promociones = pd.DataFrame({
    "nombre": ["DS Septiembre Madrid", "DS Febrero Madrid", "FS Septiembre Madrid", "FS Febrero Valencia"],
    "fecha_comienzo": ["2023-09-18", "2024-02-12", "2023-09-18", "2024-02-12"],
    "id_sede":       [1, 1, 1, 2],       # Madrid, Madrid, Madrid, Valencia
    "id_modalidad":  [2, 2, 2, 3],       # Presencial, Presencial, Presencial, Online
    "id_curso":      [1, 1, 2, 2]        # DS, DS, FS, FS
})

promociones

                 nombre fecha_comienzo  id_sede  id_modalidad  id_curso
0  DS Septiembre Madrid     2023-09-18        1             2         1
1     DS Febrero Madrid     2024-02-12        1             2         1
2  FS Septiembre Madrid     2023-09-18        1             2         2
3   FS Febrero Valencia     2024-02-12        2             3         2

### Insertamos el dataframe en la tabla 'promociones'

In [51]:
promociones.to_sql("promociones", engine, if_exists="append", index=False)

4

### Creamos el dataframe de alumnos. Para ello, se añade una columna nueva (id_promocion) a cada dataframe con el valor fijo que corresponde según la promoción

In [52]:
clase_1["id_promocion"] = 1
clase_2["id_promocion"] = 2
clase_3["id_promocion"] = 3
clase_4["id_promocion"] = 4

### Apilamos los 4 dataframes

In [53]:
alumnos = pd.concat([clase_1, clase_2, clase_3, clase_4], ignore_index=True)

### De todas las columnas que tienen los csv nos quedamos solo con las 3 que necesita la tabla

In [56]:
print(alumnos.columns.tolist())

['nombre', 'email', 'id_promocion']

In [58]:
alumnos = alumnos[["nombre", "email", "id_promocion"]]

alumnos.head()

             nombre                       email  id_promocion
0      Jafet Casals      Jafet_Casals@gmail.com             1
1  Jorge Manzanares  Jorge_Manzanares@gmail.com             1
2     Onofre Adadia     Onofre_Adadia@gmail.com             1
3      Merche Prada      Merche_Prada@gmail.com             1
4      Pilar Abella      Pilar_Abella@gmail.com             1

### Insertamos en la tabla 'alumnos'

In [59]:
alumnos.to_sql("alumnos", engine, if_exists="append", index=False)

52

### Creamos el dataframe proyectos (a mano), ya que los proyectos son nombres de columnas

In [60]:
proyectos = pd.DataFrame({
    "nombre": [
        "HLF", "EDA", "BBDD", "ML", "Deployment",      # id_curso 1 = DS
        "WebDev", "FrontEnd", "Backend", "React", "FullStack"  # id_curso 2 = FS
    ],
    "id_curso": [1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
})

proyectos

       nombre  id_curso
0         HLF         1
1         EDA         1
2        BBDD         1
3          ML         1
4  Deployment         1
5      WebDev         2
6    FrontEnd         2
7     Backend         2
8       React         2
9   FullStack         2

### Lo insertamos

In [62]:
engine.dispose() # había un problema de conexión (lo soluciono reseteando la conexión)

proyectos.to_sql("proyectos", engine, if_exists="append", index=False)

10

### Ahora toca insertar los datos en la tabla 'notas'

In [64]:
print(clase_1.columns.tolist())

['Nombre', 'Email', 'Promoción', 'Fecha_comienzo', 'Campus', 'Proyecto_HLF', 'Proyecto_EDA', 'Proyecto_BBDD', 'Proyecto_ML', 'Proyecto_Deployment', 'id_promocion']

In [ ]:
# Cargar alumnos y proyectos desde la bbdd
alumnos_db = pd.read_sql("SELECT * FROM alumnos", engine)
proyectos_db = pd.read_sql("SELECT * FROM proyectos", engine)

# Unpivot: convertir columnas de proyectos en filas
cols_ds = ["Proyecto_HLF", "Proyecto_EDA", "Proyecto_BBDD", "Proyecto_ML", "Proyecto_Deployment"]
cols_fs = ["Proyecto_WebDev", "Proyecto_FrontEnd", "Proyecto_Backend", "Proyecto_React", "Proyecto_FullSatck"]

ds = pd.concat([clase_1, clase_2], ignore_index=True)
ds_notas = ds.melt(id_vars=["Nombre"], value_vars=cols_ds, var_name="proyecto", value_name="resultado")

fs = pd.concat([clase_3, clase_4], ignore_index=True)
fs_notas = fs.melt(id_vars=["Nombre"], value_vars=cols_fs, var_name="proyecto", value_name="resultado")

notas = pd.concat([ds_notas, fs_notas], ignore_index=True)

# Limpiar nombre del proyecto y corregir errata del CSV
notas["proyecto_nombre"] = notas["proyecto"].str.replace("Proyecto_", "", regex=False)
notas["proyecto_nombre"] = notas["proyecto_nombre"].str.replace("FullSatck", "FullStack", regex=False)

# Merge para obtener id_alumno
notas = notas.merge(
    alumnos_db[["id_alumno", "nombre"]],
    left_on="Nombre",
    right_on="nombre",
    how="left"
)

# Merge para obtener id_proyecto
notas = notas.merge(
    proyectos_db[["id_proyecto", "nombre"]],
    left_on="proyecto_nombre",
    right_on="nombre",
    how="left"
)

# Solo columnas necesarias
notas = notas[["id_alumno", "id_proyecto", "resultado"]]
notas["id_proyecto"] = notas["id_proyecto"].astype(int)

# Insertar
notas.to_sql("notas", engine, if_exists="append", index=False)
print("Insertado ✓")

Insertado ✓

### Finalizamos cargando datos a la tabla 'asignaciones'

### Cargamos la tabla profesores y promociones de la base de datos

In [ ]:
profesores_db = pd.read_sql("SELECT * FROM profesores", engine)
promociones_db = pd.read_sql("SELECT * FROM promociones", engine)

print("PROFESORES:")
print(profesores_db)
print("\nPROMOCIONES:")
print(promociones_db)

PROFESORES:
   id_profesor              nombre  id_rol
0            1           Noa Yáñez       2
1            2   Saturnina Benitez       2
2            3          Anna Feliu       2
3            4       Rosalva Ayuso       2
4            5    Ana Sofía Ferrer       2
5            6     Angélica Corral       2
6            7         Ariel Lledó       2
7            8         Mario Prats       3
8            9   Luis Ángel Suárez       3
9           10  María Dolores Diaz       3

PROMOCIONES:
   id_promocion                nombre fecha_comienzo  id_sede  id_modalidad  \
0             1  DS Septiembre Madrid     2023-09-18        1             2
1             2     DS Febrero Madrid     2024-02-12        1             2
2             3  FS Septiembre Madrid     2023-09-18        1             2
3             4   FS Febrero Valencia     2024-02-12        2             3

   id_curso
0         1
1         1
2         2
3         2

### Vemos como es el dataframe claustro

In [72]:
claustro.head(10)

               Nombre Rol Vertical   Promocion    Campus   Modalidad
0           Noa Yáñez  TA       DS  Septiembre    Madrid  Presencial
1   Saturnina Benitez  TA       DS  Septiembre    Madrid  Presencial
2          Anna Feliu  TA       FS  Septiembre    Madrid  Presencial
3       Rosalva Ayuso  TA       FS  Septiembre  Valencia  Presencial
4    Ana Sofía Ferrer  TA       FS     Febrero  Valencia  Presencial
5     Angélica Corral  TA       FS     Febrero    Madrid  Presencial
6         Ariel Lledó  TA       DS  Septiembre    Madrid  Presencial
7         Mario Prats  LI       FS     Febrero  Valencia      Online
8   Luis Ángel Suárez  LI       FS  Septiembre    Madrid      Online
9  María Dolores Diaz  LI       DS  Septiembre    Madrid      Online

In [73]:
# Crear clave en claustro
claustro["promo_key"] = claustro["Vertical"] + " " + claustro["Promocion"] + " " + claustro["Campus"]

# Crear la misma clave en promociones_db
promociones_db["promo_key"] = promociones_db["nombre"]

print(claustro["promo_key"].unique())
print(promociones_db["promo_key"].unique())

<StringArray>
[  'DS Septiembre Madrid',   'FS Septiembre Madrid', 'FS Septiembre Valencia',
    'FS Febrero Valencia',      'FS Febrero Madrid']
Length: 5, dtype: str
<StringArray>
['DS Septiembre Madrid',    'DS Febrero Madrid', 'FS Septiembre Madrid',
  'FS Febrero Valencia']
Length: 4, dtype: str

In [74]:
# Merge para obtener id_profesor
asignaciones = claustro[["Nombre", "promo_key"]].copy()

asignaciones = asignaciones.merge(
    profesores_db[["id_profesor", "nombre"]],
    left_on="Nombre",
    right_on="nombre",
    how="left"
)

# Merge para obtener id_promocion
asignaciones = asignaciones.merge(
    promociones_db[["id_promocion", "promo_key"]],
    on="promo_key",
    how="left"
)

# Ver resultado antes de insertar
print(asignaciones[["Nombre", "promo_key", "id_profesor", "id_promocion"]])

               Nombre               promo_key  id_profesor  id_promocion
0           Noa Yáñez    DS Septiembre Madrid            1           1.0
1   Saturnina Benitez    DS Septiembre Madrid            2           1.0
2          Anna Feliu    FS Septiembre Madrid            3           3.0
3       Rosalva Ayuso  FS Septiembre Valencia            4           NaN
4    Ana Sofía Ferrer     FS Febrero Valencia            5           4.0
5     Angélica Corral       FS Febrero Madrid            6           NaN
6         Ariel Lledó    DS Septiembre Madrid            7           1.0
7         Mario Prats     FS Febrero Valencia            8           4.0
8   Luis Ángel Suárez    FS Septiembre Madrid            9           3.0
9  María Dolores Diaz    DS Septiembre Madrid           10           1.0

In [75]:
# Eliminar filas con NaN
asignaciones = asignaciones[["id_profesor", "id_promocion"]].dropna()
asignaciones["id_promocion"] = asignaciones["id_promocion"].astype(int)

# Insertar
asignaciones.to_sql("asignaciones", engine, if_exists="append", index=False)
print("Insertado ✓")

Insertado ✓